In [1]:
import numpy as np
matrix=[[4, 12, -16],
        [12, 37, -43],
        [-16, -43, 98]]

In [2]:
L = np.zeros_like(matrix, dtype=float)
print(L)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

def my_cholesky_decomposition(matrix):
    n = len(matrix)
    lower_triangular = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                temp_sum = sum(lower_triangular[i, k] ** 2 for k in range(j))
                lower_triangular[i, j] = np.sqrt(matrix[i, j] - temp_sum)
            else:
                temp_sum = sum(lower_triangular[i, k] * lower_triangular[j, k] for k in range(j))
                lower_triangular[i, j] = (matrix[i, j] - temp_sum) / lower_triangular[j, j]

    return lower_triangular

# Example usage
if __name__ == "__main__":
    # Create a symmetric positive definite matrix
    my_matrix = np.array([[4, 2, 14],
                          [2, 7, -5],
                          [14, -5, 83]])

    # Perform Cholesky decomposition
    my_lower_triangular = my_cholesky_decomposition(my_matrix)

    print("My Cholesky Decomposition Result:")
    print(my_lower_triangular)

My Cholesky Decomposition Result:
[[ 2.          0.          0.        ]
 [ 1.          2.44948974  0.        ]
 [ 7.         -4.89897949  3.16227766]]


In [40]:
import math
A=[[4, 2, 14],
        [2, 17, -5],
        [14, -5, 83]]
L=[[0,0,0,],[0,0,0],[0,0,0]]
m,n = len(matrix),len(matrix)
for i in range(m):
    for j in range(n):
        if(i==0):
            if(i==j):
                L[i][j]=math.sqrt(A[i][j])
                #print(L[i][j])
            else:
                #print(A[i][j]/L[i][i])
                L[j][i]=A[i][j]/L[i][i]
        if(i>0):
            #print("1",A[i][i])
            #print("2",A[i][i]-A[i][j])
            L[i][i]=math.sqrt(A[i][i]-L[i][j])
print(L)

[[2.0, 0, 0], [1.0, 4.123105625617661, 0], [7.0, 0, 8.595904049072193]]
