In [1]:
import numpy as np
def convert_to_upper_triangular_matrix():
    rows=len(matrix)
    columns=len(matrix[0])
    for i in reversed(range(rows)):
        print("operation on row ",i," for upper triangular matrix")
        for j in range(columns):
            if(j<i):
                matrix[i][j]=0
                print(matrix[i])
    #print("Final upper triangular matrix is \n",matrix)
    return matrix

In [2]:
def convert_to_lower_triangular_matrix():
    rows=len(matrix)
    columns=len(matrix[0])
    for i in reversed(range(rows)):
        print("operation on row ",i," for lower triangular matrix")
        for j in range(columns):
            if(j>i):
                matrix[i][j]=0
                print(matrix[i])
    #print("Final lower triangular matrix is \n",matrix)
    return matrix

In [3]:
m=int(input("enter number of rows for matrix"))
n=int(input("enter number of columns for matrix"))
matrix = np.random.randint(low=1, high=5, size=(m, n))
print("Original matrix \n",matrix)
uppper_t_matrix=convert_to_upper_triangular_matrix()
lower_t_matrix=convert_to_lower_triangular_matrix()
print("uppper_t_matrix \n",uppper_t_matrix)
print("lower_t_matrix \n",lower_t_matrix)

enter number of rows for matrix 3
enter number of columns for matrix 4


Original matrix 
 [[1 2 3 4]
 [3 1 4 2]
 [4 4 2 1]]
operation on row  2  for upper triangular matrix
[0 4 2 1]
[0 0 2 1]
operation on row  1  for upper triangular matrix
[0 1 4 2]
operation on row  0  for upper triangular matrix
operation on row  2  for lower triangular matrix
[0 0 2 0]
operation on row  1  for lower triangular matrix
[0 1 0 2]
[0 1 0 0]
operation on row  0  for lower triangular matrix
[1 0 3 4]
[1 0 0 4]
[1 0 0 0]
uppper_t_matrix 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 2 0]]
lower_t_matrix 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 2 0]]


In [1]:
m1=[[1,2,3],
    [3,4,2],
    [3,2,1]]

m2=[[1,1,1],
    [3,4,2],
    [3,2,1]]

In [8]:
def multiply(m1,m2):
    final_matrix=[['a','b','c'],['d','f','o'],['i','o','p']]
    val=0
    for k in range(3):
        for i in range(3):
            val=0
            for j in range (3):
                val+=m1[k][j]*m2[j][i]
            final_matrix[k][i]=val
            #print(val)
            #val=0
    print(final_matrix)

In [9]:
multiply(m1,m2)

[[16, 15, 8], [21, 23, 13], [12, 13, 8]]
